blank_issues_enabled: false
# contact_links:
#   - name: Support issue
#     url: https://github.com/nordicopen/easee_hass/discussions/categories/q-a
#     about: Please ask and answer questions here.
